### ISSUE TITLE
Factory guide refers to non-existent field for io-tape on extractors

### ISSUE THREAD

**Issue by avanier** [RAttab/legion#1]
While going through the tutorial I realized that [there's a reference](https://github.com/RAttab/legion/blob/master/res/man/guides/factory.lm#L140-L142) to the `loop` field which is not present in the UI for the `io-tape` command on extractors. Not sure if that's a documentation error, or a UI bug. The _"field"_ is available as read-only for extractors unlike in printers.

![image](https://github.com/RAttab/legion/assets/4009658/8616fdb2-5a8e-42db-9429-9d3c4b3b607f)

**Comment by RAttab** [comment]
I know what the problem is, I'll do the quick fix tomorrow :)

**Comment by RAttab** [comment]
Fixed: https://github.com/RAttab/legion/commit/ab0b5604a27b1e6159d236ce04784e865b40f9f2
