### ISSUE TITLE
Clicking the asm button in an empty mod crashes the game

### ISSUE THREAD

**Issue by avanier** [RAttab/legion#2]
How to reproduce:

* Start a new game
* Click the `mods` button
* Create `bob-the-mod` _(the bug is present in non-bob-themed mods too)_
* Click the `asm` button
* :tada: Get a free segfault! :headstone: 

---

```plaintext
[...]
GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (0), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (1), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (2), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (3), and GL_ARRAY_BUFFER_ARB, usage hint is GL_DYNAMIC_DRAW) will use VIDEO memory as the source for buffer object operations (20071)
src/engine/engine.c:100: [gl:api:other:info] Buffer detailed info: Buffer object 14 (bound to GL_ELEMENT_ARRAY_BUFFER_ARB, usage hint is GL_DYNAMIC_DRAW) will use VIDEO memory as the source for buffer object operations (20071)
[1]    491319 segmentation fault (core dumped)  ./build/legion
```

**Comment by RAttab** [comment]
Blarg, there's always a million problem in that part of the code but I should be able to hunt down the issue relatively easily tomorrow.

**Comment by RAttab** [comment]
Fixed https://github.com/RAttab/legion/commit/41e2dd6f75a9267c9055d70d2fb24c5b037589c9
Although the fixed is probably a bit brittle and I'm too tired to reload the entire state machine of the code editor to do a proper fix at the moment.
