### ISSUE TITLE
Documentation refers to non-existent compiler errors

### ISSUE THREAD

**Issue by avanier** [RAttab/legion#3]
Documentation suggests [that referring to non-existent atoms)[https://github.com/RAttab/legion/blob/master/res/man/guides/mods.lm#L167] should trigger a compilation error. This does not seem to be the case.

![image](https://github.com/RAttab/legion/assets/4009658/2e536f96-6e31-4630-8434-2748dec199cc)

I've tested with other atoms and it doesn't work either. _(I'm pretty sure `your-mum` is not a system atom.)_ The tab title goes green every time.

For reference this generates the following assembly:

```assembly
(NOOP)
(RESET)
```

**Comment by avanier** [comment]
Nevermind, I didn't see the dark red text at the bottom as I was expecting a tooltip as described ... somewhere earlier.

Works ... semi-correctly?

**Comment by RAttab** [comment]
I believe that after hitting the build button the compilation errors section should pop up and the atom should be underligned with an error tooltip on popup. I'll need to double check if that's working properly.

**Comment by RAttab** [comment]
So I tested it and the error pane does popup but the error highlighting is missing. I'll need a less tired brain to find the problem.

**Comment by RAttab** [comment]
Oh wait, I remember now, the highlighting is only for errors on the client side code parsing and not for the server side compilation. This is something I meant to improve at some point but I had other priorities and decided to revisit in the future. So yeah, currently this works as expected even though it's somewhat inconsistent behavior.

EDIT: I'm very tempted to make `your-mom` a system atom but there's no trivial way for me to do this at the moment :P
